package main

var (
	searchTweetQueries = []string{
		"nasa mars",
		"nasa simulation",
		"nasa flight",
		"space flight orbital",
		"space exploration",
		"space mars",
		"space atmosphere",
		"space traveller",
		"space observatory",
		"solar system",
		"journey mars",
		"mars colonization",
		"mars take off",
		"moon mining",
		"supermoon event space",
		"asteroid private",
		"asteroid companies",
		"asteroid physics",
		"asteroid science",
		"asteroid take off",
		"asteroids solar system",
		"asteroid universe theories",
		"asteroids comets",
		"asteroids belt",
		"asteroids ceres",
		"asteroids orbit",
		"asteroids mercury",
		"asteroids venus",
		"asteroids earth",
		"asteroids mars",
		"asteroids jupiter",
		"asteroids saturn",
		"asteroids uranus",
		"asteroids neptune",
		"asteroids around galaxy",
		"asteroids galactic tour",
		"asteroids universe",
		"asteroids space",
		"asteroids nasa",
		"asteroids deadly",
		"asteroids watch danger",
		"asteroids end world",
		"asteroids close approach",
		"asteroids strike",
		"asteroids damages earth",
		"asteroid impact simulation",
		"asteroid impact",
		"asteroids threat",
		"asteroids exploitation",
		"asteroids mining",
		"asteroid discovery",
		"Near-Earth Object Program",
	}
)
